# Generated by Django 2.1.15 on 2020-02-28 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20200226_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
