# Generated by Django 2.1.15 on 2020-03-02 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_news_publish_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('news', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='news.News')),
            ],
        ),
    ]
