# Generated by Django 2.1.15 on 2020-03-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.SlugField(default='title'),
        ),
    ]
